version: "3"

services:
  postgresql:
    container_name: prod-postgres
    build: 
      context: ./images/postgresql
      dockerfile: postgresql.Dockerfile
    ports: 
      - "5432:5432"
    volumes: 
      - ./images/postgresql/data:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: /data/postgres
    restart: unless-stopped
  mosquitto:
    container_name: prod-mosquitto
    build:
      context: ./images/mosquitto
      dockerfile: mosquitto.Dockerfile
    ports: 
      - "1883:1883"
      - "8080:8080"
    volumes: 
      - ./images/mosquitto/plugins:/mosquitto/plugins
      - ./images/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./images/mosquitto/data:/mosquitto/data
      - ./images/mosquitto/log:/mosquitto/log
    restart: unless-stopped
    depends_on: 
      - postgresql
